version: '3.8'

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - kanban-nastenka-mongo:/data/db
    networks:
      - mongo-net
  backend:
    build:
      context: backend
    ports:
      - "5001:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/backend
    networks:
      - mongo-net
    depends_on:
      - mongo
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mongo-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_BACKEND_URL=http://localhost:5001

volumes:
  kanban-nastenka-mongo:

networks:
  mongo-net: